name: Validate Application Functionality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Validate Docker image existence
        run: |
          IMAGE="charansaig1/q5:0933f79282a5e90493a440619a1bf756f51a616a"
          if docker pull $IMAGE; then
            echo "Docker image exists."
          else
            echo "Docker image does not exist!"
            exit 1
          fi

      - name: Run container and execute functional tests
        run: |
          # Set port value from GitHub secrets
          PORT="${{ secrets.PORT }}"

          # Run the Docker container in detached mode
          docker run -d -p $PORT:$PORT --name q5-container charansaig1/q5:0933f79282a5e90493a440619a1bf756f51a616a

          # Run functional tests within the container (replace with your actual test command)
          docker exec q5-container /bin/sh -c "your-functional-test-command"

      - name: Verify container is running
        run: |
          if [ $(docker ps -q -f name=q5-container) ]; then
            echo "Container is running."
          else
            echo "Container is not running."
            exit 1
          fi
