name: Docker Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables for SMS
        run: |
          echo "SMS=${{ vars.SMS }}"

      - name: Build Multi-stage Docker image
        run: |
          docker buildx build  --load \
            --build-arg PORT="${{ secrets.PORT }}" \
            -t q5 .

      - name: Tag Docker image
        run: docker tag q5 ${{ secrets.DOCKER_USERNAME }}/q5:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/q5:${{ github.sha }}

      - name: Verify Docker Image Exists
        run: docker images

      - name: Check Docker Image Size
        run: |
          IMAGE_SIZE=$(docker images --format "{{.Repository}}:{{.Tag}} {{.Size}}" | grep "${{ secrets.DOCKER_USERNAME }}/q5:${{ github.sha}}" | awk '{print $2}')
          echo "Docker Image Size: $IMAGE_SIZE"

      - name: Run Docker container
        run: |
          docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
            --name q5container ${{ secrets.DOCKER_USERNAME }}/q5:${{ github.sha }}

      - name: Verify container is running
        run: docker ps

      - name: Stop the Docker container
        run: |
          docker stop ${{ secrets.DOCKER_USERNAME }}/q5container
          docker rm ${{ secrets.DOCKER_USERNAME }}/q5container
