name: Backend Changes Workflow

on:
  push:
    paths: echo "Running tests for backend..."
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print SHA
        run: echo "The commit SHA is $GITHUB_SHA"

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Action to set up Node.js
        with:
          node-version: "16" # Specify the version of Node.js to use
      - name: Install dependencies
        run: npm install

      - name: Run backend code
        run: node backend/app.js

      - name: Test backend
        run: |
          echo "Running tests for backend..."
          if [ -f "backend/data.json" ]; then
            echo "Data file exists."
          else
            echo "Data file does not exist!"
            exit 1
          fi
