name: Docker Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables for SMS
        run: |
          echo "SMS=${{ vars.SMS }}"

      - name: Build Docker image
        run: |
          docker buildx build \
            --build-arg SMS="${{ vars.SMS }}" \
            --build-arg PORT="${{ secrets.PORT }}" \
            -t q4:latest .

      - name: Tag Docker image
        run: docker tag q4:latest q4:${{ github.sha }}

      - name: Run Docker container
        run: |
          docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
            --name q4container q4:${{ github.sha }}

      - name: Verify container is running
        run: docker ps

      - name: Stop the Docker container
        run: |
          docker stop q4container
